spring.application.name=globalinvoice
server.port=8090

spring.datasource.url=jdbc:mysql://localhost:3306/dbglobalinvoice?serverTimezone=GMT-5
spring.datasource.username=root
spring.datasource.password=

#Configuracion JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
jwt.secret.key=6fa3d0f22fab327de851890416331bc3ae2f1e7297de3097e25f27bde78f55d8
jwt.expiration.time=86400000

#Configuracion de la documentacion OpenAPI/Swagger
#OpenAPI/Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.packages-to-scan=com.jssv.globalinvoice.controller
springdoc.paths-to-match=/**
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.doc-expansion=none

#Configuracion servicio conversor SOAP
dataflex.soap.url=https://www.dataaccess.com/webservicesserver/NumberConversion.wso